[tool.poetry]
name = "planary"
version = "0.1.0"
description = ""
authors = ["dimitar <dimitar.kr.dimitrov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
