"""add column to admin table

Revision ID: 8762a90cd015
Revises: 21b47aba941f
Create Date: 2022-01-13 02:24:20.303434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8762a90cd015'
down_revision = '21b47aba941f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrators', sa.Column('description', sa.String(length=240), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('administrators', 'description')
    # ### end Alembic commands ###
