"""empty message

Revision ID: efb98b15ea16
Revises: b29bb6a666dc
Create Date: 2022-01-12 17:02:36.485499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb98b15ea16'
down_revision = 'b29bb6a666dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'demo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('demo', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
